"""Private A2 bridge contract; implementations are staged in A4 through A7."""

from collections.abc import Iterator
from itertools import takewhile

Errors = tuple[type[Exception], type[Exception], type[Exception]]
__version__: str

def _mdl_iter(lines: object) -> Iterator[object]: ...
def _metadata_iter(lines: object) -> Iterator[object]: ...
def _from_block_lines(cls: object, block_type: object, lines: object) -> object: ...
def _blocks_iter(cls: object, lines: object) -> Iterator[object]: ...
def _read_sdf_lines(sdfpath: object) -> list[str]: ...
def _records_iter(block: object) -> Iterator[tuple[str, str]]: ...
def _write(block: object, outh: object, with_newlines: object) -> None: ...
def _append_record(block: object, record_name: object, value: object) -> None: ...
def _ctable_init(table: object, lines: object, v3000: object) -> None: ...
def _parse_format(line: object, formats: object) -> object: ...
def _parse_v2000_counts(line: object) -> tuple[int, int]: ...
def _parse_v3000_counts(line: object) -> tuple[int, int]: ...
def _atomlines(table: object) -> takewhile[str]: ...
def _bondlines(table: object) -> takewhile[str]: ...
def _valid_atom_indices(
    table: object, strict: object, v3000: object, errors: Errors
) -> bool: ...
def _valid_bond_indices(
    table: object, strict: object, v3000: object, errors: Errors
) -> bool: ...
def _renumber_ctable(
    table: object, v3000: object, duplicate_error: type[Exception]
) -> None: ...
