from io import TextIOWrapper
from types import ModuleType
from typing import Iterable, Iterator, Tuple

from sendoff.ctable import CTable, CTableFormat, IndicesDuplicateError
from sendoff.sdblock import Pathy, SDBlock

__version__: str

def mdl_iter(lines: Iterable[str]) -> Iterator[str]: ...
def metadata_iter(lines: Iterable[str]) -> Iterator[str]: ...
def from_block_lines(
    cls: type[SDBlock], block_type: type[SDBlock], lines: Iterable[str]
) -> SDBlock: ...
def blocks_iter(cls: type[SDBlock], lines: Iterable[str]) -> Iterator[SDBlock]: ...
def read_sdf_lines(sdfpath: Pathy) -> list[str]: ...
def records_iter(block: SDBlock) -> Iterator[Tuple[str, str]]: ...
def write(block: SDBlock, outh: TextIOWrapper, with_newlines: bool) -> None: ...
def append_record(block: SDBlock, record_name: str, value: str) -> None: ...
def ctable_init(table: CTable, lines: Iterable[str], v3000: CTableFormat) -> None: ...
def parse_format(line: str, formats: type[CTableFormat]) -> CTableFormat: ...
def parse_v2000_counts(line: str) -> Tuple[int, int]: ...
def parse_v3000_counts(line: str) -> Tuple[int, int]: ...
def atomlines(table: CTable) -> Iterator[str]: ...
def bondlines(table: CTable) -> Iterator[str]: ...
def valid_atom_indices(
    table: CTable, strict: bool, v3000: CTableFormat, errors: ModuleType
) -> bool: ...
def valid_bond_indices(
    table: CTable, strict: bool, v3000: CTableFormat, errors: ModuleType
) -> bool: ...
def renumber_ctable(
    table: CTable, v3000: CTableFormat, duplicate_error: type[IndicesDuplicateError]
) -> None: ...
