from types import ModuleType
from typing import Iterable, Iterator, TextIO, Tuple

from sendoff.ctable import CTable, CTableFormat, IndicesDuplicateError
from sendoff.sdblock import SDBlock

__version__: str

def mdl_iter(lines: Iterable[str]) -> Iterator[str]: ...
def metadata_iter(lines: Iterable[str]) -> Iterator[str]: ...
def blocks_iter(cls: type[SDBlock], lines: Iterable[str]) -> Iterator[SDBlock]: ...
def records_iter(block: SDBlock) -> Iterator[Tuple[str, str]]: ...
def write(block: SDBlock, outh: TextIO, with_newlines: bool) -> None: ...
def append_record(block: SDBlock, record_name: str, value: str) -> None: ...
def parse_format(line: str, formats: type[CTableFormat]) -> CTableFormat: ...
def parse_v2000_counts(line: str) -> Tuple[int, int]: ...
def parse_v3000_counts(line: str) -> Tuple[int, int]: ...
def valid_atom_indices(
    table: CTable, strict: bool, v3000: CTableFormat, errors: ModuleType
) -> bool: ...
def valid_bond_indices(
    table: CTable, strict: bool, v3000: CTableFormat, errors: ModuleType
) -> bool: ...
def renumber_ctable(
    table: CTable, v3000: CTableFormat, duplicate_error: type[IndicesDuplicateError]
) -> None: ...
