[tox]
minversion = 4.24
envlist = py311, py312, py313, py314

[testenv]
package = editable
extras =
    test
deps =
    mypy==1.7.0; python_version == "3.11"
    mypy>=1.19,<2; python_version >= "3.12"
setenv =
    TMPDIR = {toxworkdir}
commands =
    python -m pytest --basetemp={envtmpdir}/pytest
    mypy sendoff tests --ignore-missing-imports --strict

[gh-actions]
python =
    3.11: py311
    3.12: py312
    3.13: py313
    3.14: py314
